#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/lib/yard-tomdoc/version'

name    "yard-tomdoc"
version YARD::TomDoc::VERSION
title   "YARD TomDoc"
summary "TomDoc for YARD"

description "Use TomDoc documentation format with YARD."

authors [
  'Thomas Sawyer <transfire@gmail.com>',
  'Loren Segal'
]

requirements [
  'yard',
  'detroit  (build)',
  'rake     (test)',
  'minitest (test)',
  #'tomdoc 0.2.0+'
]

resources(
  'home' => 'http://rubyworks.github.com/yard-tomdoc',
  'code' => 'http://github.com/rubyworks/yard-tomdoc',
  'docs' => 'http://rubyworks.github.com/yard-tomdoc/doc'
)

copyrights [
  '2010 Loren Segal (MIT)' 
]

